module.exports = (sequelize, Sequelize) => {
  const Device = sequelize.define("device", {
    email: { type: Sequelize.STRING },
    ip: { type: Sequelize.STRING },
    isp: { type: Sequelize.STRING },
    country: { type: Sequelize.STRING },
    screen_resolution: { type: Sequelize.STRING },
    color_depth: { type: Sequelize.STRING },
    lang: { type: Sequelize.STRING },
    timezone: { type: Sequelize.STRING },
    cpu_cores: { type: Sequelize.STRING },
    device_memory: { type: Sequelize.STRING },
    network_type: { type: Sequelize.STRING },
    is_mobile: { type: Sequelize.STRING },
    hardware_vendor: { type: Sequelize.STRING },
    hardware_model: { type: Sequelize.STRING },
    hardware_name: { type: Sequelize.STRING },
    device_type: { type: Sequelize.STRING },
    platform_vendor: { type: Sequelize.STRING },
    platform_name: { type: Sequelize.STRING },
    platform_version: { type: Sequelize.STRING },
    browser_vendor: { type: Sequelize.STRING },
    browser_name: { type: Sequelize.STRING },
    browser_version: { type: Sequelize.STRING },
    hardware_rank: { type: Sequelize.STRING },
    is_tablet: { type: Sequelize.STRING },
    screen_width_px: { type: Sequelize.STRING },
    screen_height_px: { type: Sequelize.STRING },
    has_touch_screen: { type: Sequelize.STRING },
    has_camera: { type: Sequelize.STRING },
    is_tv: { type: Sequelize.STRING },
    is_smartphone: { type: Sequelize.STRING },
    is_small_screen: { type: Sequelize.STRING },
    has_nfc: { type: Sequelize.STRING },
    hardware_family: { type: Sequelize.STRING },
    oem: { type: Sequelize.STRING },
    is_screen_foldable: { type: Sequelize.STRING },
    platform_rank: { type: Sequelize.STRING },
    has_geo_location: { type: Sequelize.STRING },
    is_email_browser: { type: Sequelize.STRING },
    is_emulating_device: { type: Sequelize.STRING },
    is_crawler: { type: Sequelize.STRING },
    is_ia: { type: Sequelize.STRING },
    device_id: { type: Sequelize.STRING }
  },
  {
    tableName: 'device_data',
  });

  return Device;
};
